CV-7-feature/test-api-response
jesuslife/repo-test pull request #19
Opened 2024-08-14 22:53 UTC by jesuslife

client.py to test api response created

2024-08-14 23:59 UTC, J-Jerry requested changes

2024-08-14 23:59 UTC, J-Jerry commented on code/predict.py
seed should be different

2024-08-15 00:02 UTC, jesuslife commented on code/predict.py
that works fine

2024-08-15 00:03 UTC, J-Jerry approved these changes
all ok

2024-08-15 00:03 UTC, closed without merging